name: 'Manage Github Secrets'
description: 'Creates, manages, updates repository secrets, environment variables and outputs for use within other actions'
author: 'Videndum'
branding:
  icon: 'at-sign'
  color: 'purple'
inputs:
  settings:
    required: false
    description: 'Settings to be passed'
  settingsjson:
    required: false
    description: 'JSON file to be passed'
    default: '.github/allconfigs.json'
  mode:
    required: true
    description: 'Sets the mode of the action - Output, Secrets, Environment'
    default: 'outputs'
  secretOrg:
    required: true
    description: 'If set to true, will update the "SETTINGS" secret within the organisation instead'
    default: 'false'
  secretupdates:
    required: true
    description: 'If set to true, will update the "SETTINGS" secret within the repository'
    default: 'false'
  secretname:
    required: false
    description: 'sets the secret name to be used for settings secret'
    default: 'SETTINGS'
  token:
    required: true
    description: 'The token that should be used (NEEDS be a personal access token)'
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'
