name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
#   build: # make sure build/ci work properly
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: |
#           npm install
#       - run: |
#           npm run all
               
  test-output: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    outputs: 
      test: ${{steps.tests.outputs.inclusive_comment}}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: tests
        with:
          settings: ${{ secrets.SETTINGS }}
          settingsjson: '.github/allconfigs.json'
          mode: 'output'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: check output
        run: echo "${{steps.tests.outputs.inclusive_comment}}"

  test-env: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: test-output
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          settings: ${{ secrets.SETTINGS }}
          settingsjson: '.github/allconfigs.json'
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: check env
        run: echo "${{env.inclusive_comment}}"
      - name: check output
        run: |
          echo "${{needs.test-output.test}}"
